### ISSUE TITLE
Getting "Whoops, looks like something went wrong." after trying to add a new category

### ISSUE THREAD

**Issue by nigellima** [akaunting/akaunting#211] opened 2018-02-08 15:08 UTC
When I installed the system in my server, the table 'n2f_categories' came with some registers already created. While testing the features, I tried to edit the type of one of the categories and I got the exception page "Whoops, looks like something went wrong.", but no error was shown in the rest of the page. And after that, I couldnt open the page setting->categories anymore.

Then, I truncated the table to start creating new categories and avoid the error. After I did that, I was able to open the categories page again. But, again, after I tried to create a new category, I got the error page. When I went to check in database the 'n2f_categories' table, the data I tried to create was there, but I cant open the categories page again.

What's causing this issue?

I appreciate any help. Thanks in advance!

**Comment by sebadamus** [comment] 2018-02-08 16:51
Yup, it happend to me too when trying to change the Category "Transference" from Type: Other, to Type: Item for i.e. (anyway going back with the browser could change back the Type and works again)

Here the complete whoops...



(2/2)                                         ErrorException                                                                          Object  of class Illuminate\Database\Eloquent\Builder could not be converted to  int (View:  /var/www/html/akaunting/resources/views/settings/categories/index.blade.php)
--
in dae0ac774662019869fcf386e2233ccca3619969.php (line 66)
at CompilerEngine->handleViewException(object(ErrorException), 1)in PhpEngine.php (line 44)
at PhpEngine->evaluatePath('/var/www/html/akaunting/storage/framework/views/dae0ac774662019869fcf386e2233ccca3619969.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'categories' => object(LengthAwarePaginator), 'types' => object(Collection), 'transfer_id' => object(Builder), 'date_format' => 'd M Y', 'limits' => array('10', '25', '50', '100'), 'this_year' => 2018, 'years' => array(2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014)))in CompilerEngine.php (line 59)
at CompilerEngine->get('/var/www/html/akaunting/resources/views/settings/categories/index.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'categories' => object(LengthAwarePaginator), 'types' => object(Collection), 'transfer_id' => object(Builder), 'date_format' => 'd M Y', 'limits' => array('10', '25', '50', '100'), 'this_year' => 2018, 'years' => array(2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014)))in View.php (line 137)
at View->getContents()in View.php (line 120)
at View->renderContents()in View.php (line 85)
at View->render()in Response.php (line 38)
at Response->setContent(object(View))in Response.php (line 200)
at Response->__construct(object(View))in Router.php (line 615)
at Router->prepareResponse(object(Request), object(View))in Router.php (line 572)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in LaratrustPermission.php (line 56)
at LaratrustPermission->handle(object(Request), object(Closure), array('read-settings-categories'))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in LaratrustPermission.php (line 56)
at LaratrustPermission->handle(object(Request), object(Closure), array('read-admin-panel'))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AdminMenu.php (line 187)
at AdminMenu->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SetLocale.php (line 94)
at SetLocale->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddXHeader.php (line 18)
at AddXHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in LoadCurrencies.php (line 43)
at LoadCurrencies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in LoadSettings.php (line 58)
at LoadSettings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in RedirectIfNotInstalled.php (line 21)
at RedirectIfNotInstalled->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php (line 43)
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 574)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 533)
at Router->dispatchToRoute(object(Request))in Router.php (line 511)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php (line 51)
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php (line 56)
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Request.php (line 111)
at Request->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 27)

**Comment by nigellima** [comment] 2018-02-08 17:07
Hi @sebadamus. Were you albe to fix it?

**Comment by sebadamus** [comment] 2018-02-08 20:32
Not really (I am starting with the development environment), just could went back and change to the original value (or phpmyadmin to edit the database manually) 
Try not to touch the default Categories Types for the time being. 
@denisdulici may try later on with updates if its ok! (may be blocking these default Categories Types)

**Comment by nigellima** [comment] 2018-02-09 12:24
@denisdulici Could you give us some tip about getting this issue fixed? I have one version of your system running on my server

**Comment by denisdulici** [comment] 2018-02-09 15:12
I'm not able to reproduce such an issue. I was able to create, edit and filter categories. A **step-by-step** and summary guide may help further.

**Comment by sebadamus** [comment] 2018-02-09 17:43
Hi @denisdulici, I test it yesterday before lasts commits and the error happened... but I have git pull later and now I re-test and no error 👍 , so... it might be fixed with the latest updates.  @nigellima could you re-test with latest commit? if it works fine now... we can close the issue.

**Closed** 2018-02-19 14:12 UTC
