### ISSUE TITLE
Empty filters are gone in 2.0.4

### ISSUE THREAD

**Issue by jleu84** [akaunting/akaunting#1349] opened 2020-03-12 05:59 UTC
#357 # Steps to reproduce the issue
It is no longer possible to show data for example for the whole previous year. Install or update to 2.0.4. Check filters. Filters are predefined and always select a value. It is no longer possible to leave a filter empty and show whole data.

### Expected result
Default filter with actual year, but no other predefined filters

### Actual result
Default filter filters actual year an first value of filter cathegory.

### System information (Akaunting, PHP versions)
2.0.4

### Additional comments
Same issue found on forum -> 
https://akaunting.com/forum/discussion/installation-update/report-filters0

**Comment by denisdulici** [comment] 2020-03-19 16:50
Duplicate of #1346

**Closed by denisdulici** 2020-03-19 16:50 UTC
