### ISSUE TITLE
Having slow response issues when using app in LAN without internent.

### ISSUE THREAD

**Issue by FahadMaqbool** [akaunting/akaunting#852] opened 2019-07-31 06:19 UTC
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
I have installed it on a system within a LAN that has a domain network. 
I have configured the app on PC and the web app is up and running on localhost it works fine and loads fine until I plugin the network cable and the system becomes part of the LAN/ local domain network. I am unable to comprehend if I have to change something with the web application settings. Infact, I am running another web application that is even larger than akaunting, but it works perfectly fine. I need to know the solution If anyone please help. Thanks

### Expected result

It should be responding quickly. 

### Actual result

I get response in 40 to 60 seconds. 

### System information (Akaunting, PHP versions)

XAMMP latest, Akauting latest downloaded from your website 3 days ago.

### Additional comments
![issue1](https://user-images.githubusercontent.com/15454974/62188173-0b1d4280-b385-11e9-9c8c-eac83b776928.PNG)
![issue2](https://user-images.githubusercontent.com/15454974/62188175-0b1d4280-b385-11e9-9c66-11bfebfc46d6.PNG)

**Comment by FahadMaqbool** [comment] 2019-07-31 06:20
can see that when I plugin the cable and see the response from from the developers tools it shows me the following two connections that take too much time. I understand that application is looking for something to fetch from the internet and it cannot get it back as the attached image shows; It is not getting the fonts from googleapis but what is causing more waiting time is the loading of first page every time. Hope to get a response from you.

**Comment by denisdulici** [comment] 2019-07-31 07:35
Duplicate of the forum.

**Closed by denisdulici** 2019-07-31 07:35 UTC

**Comment by FahadMaqbool** [comment] 2019-08-01 04:58
Hi, I have not got got any answer on forum as well as on GITHUB. Kindly help.
    On Wednesday, July 31, 2019, 12:35:46 PM GMT+5, Denis Duliçi <notifications@github.com> wrote:  
 
 
Closed #852.

**Comment by FahadMaqbool** [comment] 2019-08-01 05:00
I did not find the answer for what I was looking for. I am using the app in a local network and there is no internet connection. everything loads fine when PC is not connected to LAN/Domain Network. but it gets really slow when I connect it to the LAN. I am running another website but there wasn't any issue for that app.
