### ISSUE TITLE
Settings Currencies Japan Error

### ISSUE THREAD

**Issue by Douglasproglima** [akaunting/akaunting#815] opened 2019-04-07 14:12 UTC
https://akaunting.com/forum/discussion/development/settings-currencies-japan-error

### Steps to reproduce the issue
I am having trouble using JP - Yen. In Japan, you do not use "Precision" or "the Japanese yen doesn't use a minor unit".

Example:
var number = 123456.789;

// the Japanese yen doesn't use a minor unit
console.log(new Intl.NumberFormat('ja-JP', { style: 'currency', currency: 'JPY' }).format(number));

// expected output: "￥123,457"
Then when editing an Expenses->Payments post, the system deletes the decimal values, for example:
Value ￥1,596
https://prntscr.com/n3dk4y

With the form open(Edit Payments):
https://prnt.sc/n3dnv0

The toLocaleString() method returns a string with a language-sensitive representation of this number:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

function eJapan(x){
  return x.toLocaleString('ja-JP');
}

console.log(eJapan(123456));

// expected output: "123,456"
console.log(eJapan("123456"));

// expected output: "123456"
console.log(eJapan(NaN));

// expected output: "NaN"
/*CONSOLE LOG RETURN*/
> "123,456" > "123456" > "NaN"

https://prnt.sc/n3dpb5

### Expected result
After editing the value according to image:
https://prntscr.com/n3dk4y

### Actual result
https://prntscr.com/n3dk4y

With the form open(Edit Payments):
https://prnt.sc/n3dnv0

### System information (Akaunting, PHP versions)
PHP 7.0
Akaunting Version 1.3.16

### Additional comments
The Japanese Yen doesn't use a minor unit

**Comment by denisdulici** [comment] 2019-04-08 18:17
Duplicate of forum.

**Closed by denisdulici** 2019-04-08 18:17 UTC

**Comment by Douglasproglima** [comment] 2019-04-09 06:29
Sorry, but you did not answer the first question.
