### ISSUE TITLE
Regression: Can't filter revenues or expenses in v2

### ISSUE THREAD

**Issue by blackpidgeon** [akaunting/akaunting#1327] opened 2020-03-04 15:44 UTC
### Steps to reproduce the issue
Try to filter revenues, for example by category.

### Expected result
It used to be a feature in 1.3.18

### Actual result
Doesn't work anymore in 2.0.3

### System information (Akaunting, PHP versions)
2.0.3, PHP 7.2

**Comment by denisdulici** [comment] 2020-03-19 16:50
Duplicate of #1346

**Closed by denisdulici** 2020-03-19 16:50 UTC
