### ISSUE TITLE
No Datetime Conversion of EXIF data

### ISSUE THREAD

**Issue by milou12345** [akaunting/akaunting#2000] opened 2021-04-23 15:37 UTC
### Steps to reproduce the issue
1. Add a photo with EXIF shooting date in format dd.mm.yy to an item.

### Expected result
Generate new Item

### Actual result
Sql error:

SQLSTATE[22007]: Invalid date time format: 1366 Incorrect integer value: '' for column `akaunting`.`mediables`.`media_id` at row 1 (SQL: insert into `mediables` (`media_id`, `mediable_id`, `mediable_type`, `order`, `tag`) values (, 7, App\Models\Common\Item, 1, picture))

### System information (Akaunting, PHP versions)
Akaunting Docker akaunting/akaunting
MariaDB

Removing the EXIF data lets you add the photo to an item

**Comment by denisdulici** [comment] 2021-04-24 12:38
Duplicate of forum.

**Closed by denisdulici** 2021-04-24 12:38 UTC
