### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by donny26utama** [akaunting/akaunting#2371] opened 2022-03-07 09:15 UTC
### Akaunting version

2.1.20

### PHP version

7.4.16

### Operating system

Windows 10

### Steps to reproduce

I'm using MAMP NGINX.
- create new host e.g akaunting.local
- pointing root directory e.g D:/www/akaunting
- open the host

I have tried installing fresh Laravel and reproducing the step above.
and the host works properly. 

I guess, there is a problem when putting file index.php into the root.
what I am missing?

### Expected result

show login page

### Actual result

![image](https://user-images.githubusercontent.com/13846150/157001982-caac53a2-558a-40d7-a3e8-5bd7b58a749d.png)

**Comment by rihards-simanovics** [comment] 2022-03-07 09:18
Can you post your Nginx conf file here?

**Comment by rihards-simanovics** [comment] 2022-03-07 09:20
sample Nginx config is here: [https://github.com/akaunting/akaunting/blob/master/nginx.example.com.conf.](https://github.com/akaunting/akaunting/blob/master/nginx.example.com.conf).

Also, have you installed PHP and added it to the path var?

**Comment by donny26utama** [comment] 2022-03-07 09:44
> Can you post your Nginx conf file here?

```
server {
        #listen   80; ## listen for ipv4; this line is default and implied
        #listen   [::]:80 default ipv6only=on; ## listen for ipv6

        server_name "akaunting.local";
		root "C:/MAMP/htdocs/akaunting"; 
		access_log  "C:/MAMP/logs/nginx_access.log";
		error_log  "C:/MAMP/logs/nginx_error.log";

		listen 8001 ;     #ssl
				#ssl_certificate     
		     #ssl_certificate_key 
	    #ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
        #ssl_ciphers         'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
        #ssl_prefer_server_ciphers  on;

		location / {
			try_files       $uri $uri/ /index.php$is_args$args;
            index           index.php;
            autoindex       on;
        }
		location ~ \.php$ {
			try_files       $uri =404;
			fastcgi_pass     127.0.0.1:9100;
			fastcgi_param    SCRIPT_FILENAME $document_root$fastcgi_script_name;
			include          fastcgi_params;
		}
	}
```
its generating by MAMP. I dont have change anything there.
and also I have set PHP in my `System Variable` path.

**Comment by rihards-simanovics** [comment] 2022-03-07 09:48
That Server name is listening on `port 8001` or locally on `port 9100`. Try these and see if you get any results.

**Comment by donny26utama** [comment] 2022-03-07 09:56
> That Server name is listening on `port 8001`. To access the server locally using `127.0.0.1` use `port 9100`. Try these and see if you get any results.
> 
> So try either: `akaunting.local:8001` or `127.0.0.1:9100`

ahh,, now it works. thanks.

**Comment by rihards-simanovics** [comment] 2022-03-07 12:01
> > That Server name is listening on `port 8001`. To access the server locally using `127.0.0.1` use `port 9100`. Try these and see if you get any results.
> > So try either: `akaunting.local:8001` or `127.0.0.1:9100`
> 
> ahh,, now it works. thanks.

@donny26utama, please don't forget to close this ticket since the issue is resolved.

**Comment by cuneytsenturk** [comment] 2022-03-29 06:33
@rihards-simanovics Thank for helping.

**Closed by cuneytsenturk** 2022-03-29 06:33 UTC
