### ISSUE TITLE
Attachment file on invoice cannot be open

### ISSUE THREAD

**Issue by aufche** [akaunting/akaunting#2128] opened 2021-06-22 04:34 UTC
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Insert attachment file, but cannot open the file ( i.e image) 

### Expected result

We can open the file,not download. Just view

### Actual result

Just download and delete

### System information (Akaunting, PHP versions)
2.1.7
Php 7.4

### Additional comments

Nope

**Comment by denisdulici** [comment] 2021-06-22 07:20
Duplicate of forum.

**Closed by denisdulici** 2021-06-22 07:20 UTC
