### ISSUE TITLE
Search/Filter not working

### ISSUE THREAD

**Issue by aliuysal60** [akaunting/akaunting#1346] opened 2020-03-10 18:33 UTC
### Steps to reproduce the issue

Open Invoices Lists
search any word

### Actual result

no data

### System information (Akaunting, PHP versions)
2.0.4
PHP 7.4

### Additional comments

Invoices and Purchases, Customers, Vendors. The search box in their list is not working

![image](https://user-images.githubusercontent.com/6507261/76346825-b7a9a480-6316-11ea-976b-13b73d25719c.png)

**Comment by innovusvm** [comment] 2020-03-11 12:24
Same problem here! Also in previous versions was very helpful the hability to filter by customer and status.

**Comment by alex-phillips** [comment] 2020-03-19 20:13
Also filtering by date range in the previous version was quite useful

**Comment by dungeonist** [comment] 2020-05-24 02:39
Same here. I can't filter data in invoice and expenses area. Any word or information return a "No Data" as in the screenshot of the bug report.

**Comment by alanbrande** [comment] 2020-05-29 21:34
Not working for me also, would be great to be able to filter per column as it was before.

**Comment by simkea** [comment] 2020-06-05 13:19
Is anyone currently working on this problem?
I can confirm, the internal search in the listings does not work.
There is no query/ajaxcall to the server.

**Comment by fatihalp** [comment] 2020-06-30 20:37
Most basic filter is not working for months even on cloud. I believe it's urgent and blocker issue @cuneytsenturk

**Comment by alex-phillips** [comment] 2020-07-01 14:26
Agreed. This is the sole reason I still haven't upgraded to v2...

**Comment by hexmarkrecords** [comment] 2020-07-18 04:18
This feature is core to the accounting platform. We need reports based on a period to file taxes.

**Comment by aletfox** [comment] 2020-08-03 23:32
anyone know the status of this bug?

**Comment by domaniEquestrian** [comment] 2020-08-05 07:09
We are facing the same issue..

**Comment by fatihalp** [comment] 2020-08-05 10:47
Isn't it most basic need @denisdulici ? 

How I'll find my customer in 10.000 customer? Shoud be urgent?

**Comment by vrielsa** [comment] 2020-08-07 07:59
I'm working on a PR for this. 
I'll try to finish it tonight.

**Comment by hexmarkrecords** [comment] 2020-08-07 11:18
When fixed do you know how long it takes to make it to production?

**Comment by regedittap** [comment] 2020-09-12 10:41
Hi any update on this bug?

**Comment by 3run01** [comment] 2020-09-25 02:19
Oi alguma atualização sobre este bug?

**Comment by 3run01** [comment] 2020-09-25 02:19
Hi any update on this bug?

**Comment by mehdi89** [comment] 2020-09-28 19:50
Any update here? it seems updating to the latest version was a mistake. I don't understand why such an important feature was missing in the first place. 

The basic filter itself and Filter by date and each column.

**Comment by jleu84** [comment] 2020-11-08 14:57
Landed here because of Issue #1454 which is still not resolved and which is the reason I am still running version 1.3.18. Why is there no update about this filter issue? In my opinion it is better to communicate. No matter what is the reason of this big delay. Ignoring the consumers creates an uncomfortable feeling.

**Comment by denisdulici** [comment] 2020-11-11 12:00
Implemented via #1657

**Closed by denisdulici** 2020-11-11 12:00 UTC
Labels: Bug

**Comment by jleu84** [comment] 2020-11-21 19:51
Is it working for someone? I updated to the newest vdrsion on my dev environment, but i still can't have a complete overview without any filters set.

**Comment by o---** [comment] 2021-01-01 23:30
> Is it working for someone? I updated to the newest vdrsion on my dev environment, but i still can't have a complete overview without any filters set.

Just installed 2.1.0 and the answer to your question is: NO. Its still very much broken. See my test results - Those filters are not working as expected.  

![image](https://user-images.githubusercontent.com/5457048/103447855-1028a480-4c91-11eb-9510-420f0348d842.png)

![image](https://user-images.githubusercontent.com/5457048/103447873-71e90e80-4c91-11eb-9e1b-2715d50d58db.png)

![image](https://user-images.githubusercontent.com/5457048/103447875-7c0b0d00-4c91-11eb-9ab6-a14de4cd1487.png)

**Comment by aletfox** [comment] 2021-01-05 16:52
This is a big problem, the filters are very important when we handle many transactions and it is a way to quickly locate the client, the invoice or the item, I use it in production and I have not been able to migrate due to this inconvenience, from a practical point of view, How do the creators propose that we consult a transaction from 6 months ago and that has at least 3,000 more transactions?
