### ISSUE TITLE
Error after update to 2.1.14

### ISSUE THREAD

**Issue by pe3dr0o** [akaunting/akaunting#2052] opened 2021-05-21 21:27 UTC
### Steps to reproduce the issue

Click to update Akaunting

### Expected result

Akaunting updated

### Actual result

I have updated my Akaunting 2.1.13 to 2.1.14 from Dashboard but unfortunately, it's come with an error and whenever I try to log in it shows Page Not Found.

I've just set APP_URL properly.

Screenshot: https://ibb.co/gMBGZRS

![errorakauting](https://user-images.githubusercontent.com/84601838/119199794-13ff6c80-ba62-11eb-982a-fd862b1cf5cb.png)

### System information (Akaunting, PHP versions)

PHP 7.4
DigitalOcean
Akaunting 7.1.13

**Comment by pe3dr0o** [comment] 2021-05-21 21:53
![Uploading image.png…]()

**Comment by pe3dr0o** [comment] 2021-05-21 21:53
![image](https://user-images.githubusercontent.com/84601838/119201718-d69cde00-ba65-11eb-887a-0d78e08536f6.png)

**Comment by denisdulici** [comment] 2021-05-23 16:23
Duplicate of forum.

**Closed by denisdulici** 2021-05-23 16:23 UTC

**Comment by SkullMasher** [comment] 2021-05-24 22:56
> Duplicate of forum.

The forum link @denisdulici might be refering to https://akaunting.com/forum/discussion/installation-update/error-after-upgrade-to-2114

**Comment by SkullMasher** [comment] 2021-05-25 00:41
@pe3dr0o I just detailed the step I did to solve the issue [in this forum answer](https://akaunting.com/forum/discussion/installation-update/error-after-upgrade-to-2114?page=3#12498). Cheers.
