### ISSUE TITLE
Item Import Error

### ISSUE THREAD

**Issue by amitrons** [akaunting/akaunting#483] opened 2018-09-12 08:06 UTC
Dear Sir,

I do not import any item. It is show error. The error is Error: The enabled field must be true or false. Sheet name: items. Line number: 2.  Pls tell me how i solved my problem or give me a good solution.

**Comment by denisdulici** [comment] 2018-09-12 08:31
Duplicate of forum.

**Closed by denisdulici** 2018-09-12 08:31 UTC
