### ISSUE TITLE
Independent reporting screens

### ISSUE THREAD

**Issue by seferdemirci** [akaunting/akaunting#1536] opened 2020-07-16 12:35 UTC
### Steps to reproduce the issue

In the reporting section, we cannot select blank option. For instance; I would like to monitor Expenses belonging to the only a year without being dependent on "Account", "Vendor", "Expense Category" or "Project" (I have Projects App). But I can't, because I have to choose an option from "Account", "Vendor", "Expense Category" or "Project" dropdowns.

When you think, on the contrary, you encounter the same situation. For instance; If you would like to see the report by the only Vendor (as independent other dropdowns in "Year", "Account", "Expense Category" or "Project" ), you could not.

### Expected result

We are expecting to add blank options to "Year", "Account", "Vendor", "Expense Category" or "Project" dropdowns to the reporting. (Independently of each other)

**Also is the same Income Reporting section.**

### Actual result

![image](https://user-images.githubusercontent.com/63615719/87670991-4b81f600-c779-11ea-8cff-4931a27f57fd.png)

### System information (Akaunting, PHP versions)

Akaunting 2.0.16, PHP 7.4

**Comment by denisdulici** [comment] 2020-07-19 09:23
Duplicate of #1346

**Closed by denisdulici** 2020-07-19 09:23 UTC
