### ISSUE TITLE
Add New Currency Symbol in Settings Page

### ISSUE THREAD

**Issue by yuvraj131** [akaunting/akaunting#1505] opened 2020-06-25 15:44 UTC
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Go to Settings, Currency, Add New Currency. 

### Expected result

The page should allow adding a custom currency such as Bitcoin or other currency along with its Symbol. 

### Actual result

The result is that it is only showing pre-configured currency symbols and not letting to add new symbol. 

### System information (Akaunting, PHP versions)

Php version 7.03

### Additional comments

The idea is to add and operate bitcoin or similar currency in accounting.

Any help in this matter is greatly appreciated. 

Thanks in advance.

**Comment by denisdulici** [comment] 2020-06-29 11:08
Duplicate of forum.

**Closed by denisdulici** 2020-06-29 11:08 UTC
