### ISSUE TITLE
Mobile Menu breaks

### ISSUE THREAD

**Issue by NDMartin** [akaunting/akaunting#1930] opened 2021-03-12 18:14 UTC
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1) Visit Akaunting on a mobile fun. 
2) Scroll to the top.

### Expected result

You should be able to open and close your menu easily.

### Actual result

You can't close or open your sidebar/menu because the search & support icons etc are shown above
See https://ibb.co/Cv2Z422
It only works when you scroll down, so you don't have the icons 'in the way'

### System information (Akaunting, PHP versions)
Version 2.1.7

**Comment by denisdulici** [comment] 2021-03-17 09:31
Duplicate of #1916

**Closed by denisdulici** 2021-03-17 09:31 UTC
