### ISSUE TITLE
Missing translation strings to months in reports

### ISSUE THREAD

**Issue by thunoldolsen** [akaunting/akaunting#674] opened 2018-12-10 13:10 UTC
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
When viewing reports i norwegian language, the months are shown with english language. I can either see them as a translation strings in crowdin.

### Expected result
Norwegian translated months in reports

### Actual result
English translated months in reports

### System information (Akaunting, PHP versions)
1.3.4 PHP 7.2

### Additional comments
I need the translation strings for months to the reports in Crowdin. Then I will translate them to the correct language.

**Comment by denisdulici** [comment] 2018-12-11 13:41
Those translations come from ChartJS library. I can reproduce the issue and will investigate it further.

**Comment by mocig** [comment] 2020-04-10 22:44
> Those translations come from ChartJS library. I can reproduce the issue and will investigate it further.

They come from Carbon which is used to overwrite the Date class.

But when i change my user to nb-NO language, the reports use the propper translation and not english:

![image](https://user-images.githubusercontent.com/29002227/79027653-4eea5d80-7b4a-11ea-8099-efd971b07ba7.png)

Since that post is from 2018 i think this one is solved and never got marked as solved.

**Comment by denisdulici** [comment] 2020-04-10 23:14
Yep, it may be fixed in 2.0 so @thunoldolsen can you please confirm this?

**Comment by mocig** [comment] 2020-04-10 23:42
I'm using Version 2.0.8 and month names are def. translated.

**Closed** 2020-04-18 16:22 UTC
